### ISSUE TITLE
Multiple Entry Points Released?

### ISSUE THREAD

**Issue by moishinetzer** [raulfdm/vite-3-lib-multiple-entrypoints#1]
https://vitejs.dev/guide/build.html#library-mode

```js
// vite.config.js
import { resolve } from 'path'
import { defineConfig } from 'vite'

export default defineConfig({
  build: {
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, 'lib/main.js'),
      name: 'MyLib',
      // the proper extensions will be added
      fileName: 'my-lib'
    }...
```

As you can see, they mention:
``` js
// Could also be a dictionary or array of multiple entry points
```

Correct me if I'm wrong, but I believe it is now supported.

**Comment by raulfdm** [comment]
Indeed it's supported. I've added a update note on my article + added this as example.

There's only one caviat which is for UMD files but so far it's working fine on vite 3.2

https://www.raulmelo.dev/blog/build-javascript-library-with-multiple-entry-points-using-vite-3
